services:

  database:
    image: postgres:16-alpine
    container_name: textile-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: textile123
      POSTGRES_DB: textile_waste_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


  backend:
    build:
      context: ./backend

    container_name: textile-backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:textile123@database:5432/textile_waste_db

    volumes:
      - ./backend:/app

    depends_on:
      - database

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend

    container_name: textile-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped


volumes:
  postgres_data: