import { useEffect, useState } from "react";

import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";

import {
  FaChartBar,
  FaUsers,
  FaIndustry,
  FaRecycle,
  FaBoxes,
  FaClipboardList,
  FaDownload,
  FaSyncAlt,
  FaChartLine,
  FaWeightHanging,
} from "react-icons/fa";

import "../css/AdminReports.css";

function AdminReports() {
  const [collapsed, setCollapsed] = useState(false);
  const [loading, setLoading] = useState(false);

  const [stats, setStats] = useState({
    total_users: 0,
    admins: 0,
    manufacturers: 0,
    recyclers: 0,
    managers: 0,
    inventory: 0,
    pending: 0,
    processing: 0,
    completed: 0,
    total_waste: 0,
  });

  const [monthlyWaste, setMonthlyWaste] = useState([]);

  const [wasteTypes, setWasteTypes] = useState([]);

  // =========================================================
  // LOAD REPORT DATA
  // =========================================================

  const loadReports = async () => {
    setLoading(true);

    try {
      const dashboardResponse = await fetch(
        "http://127.0.0.1:8000/admin/dashboard"
      );

      if (dashboardResponse.ok) {
        const dashboardData = await dashboardResponse.json();

        setStats({
          total_users: dashboardData.total_users || 0,
          admins: dashboardData.admins || 0,
          manufacturers: dashboardData.manufacturers || 0,
          recyclers: dashboardData.recyclers || 0,
          managers: dashboardData.managers || 0,
          inventory: dashboardData.inventory || 0,
          pending: dashboardData.pending || 0,
          processing: dashboardData.processing || 0,
          completed: dashboardData.completed || 0,
          total_waste: dashboardData.total_waste || 0,
        });
      }

      const monthlyResponse = await fetch(
        "http://127.0.0.1:8000/admin/monthly-waste"
      );

      if (monthlyResponse.ok) {
        const monthlyData = await monthlyResponse.json();

        setMonthlyWaste(
          Array.isArray(monthlyData)
            ? monthlyData
            : []
        );
      }

      const typesResponse = await fetch(
        "http://127.0.0.1:8000/admin/waste-types"
      );

      if (typesResponse.ok) {
        const typesData = await typesResponse.json();

        setWasteTypes(
          Array.isArray(typesData)
            ? typesData
            : []
        );
      }
    } catch (error) {
      console.error(
        "Failed to load admin reports:",
        error
      );

      // Demo fallback data
      setMonthlyWaste([
        { month: "Jan", waste: 120 },
        { month: "Feb", waste: 180 },
        { month: "Mar", waste: 240 },
        { month: "Apr", waste: 300 },
        { month: "May", waste: 370 },
        { month: "Jun", waste: 450 },
      ]);

      setWasteTypes([
        {
          name: "Cotton",
          value: 420,
        },
        {
          name: "Polyester",
          value: 310,
        },
        {
          name: "Denim",
          value: 240,
        },
        {
          name: "Wool",
          value: 150,
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  // =========================================================
  // DOWNLOAD REPORT
  // =========================================================

  const downloadReport = () => {
    const report = `
TEXTILE WASTE AI
ADMINISTRATION REPORT
========================================

USER STATISTICS

Total Users: ${stats.total_users}
Administrators: ${stats.admins}
Manufacturers: ${stats.manufacturers}
Recyclers: ${stats.recyclers}
Managers: ${stats.managers}

WASTE STATISTICS

Inventory Records: ${stats.inventory}
Pending: ${stats.pending}
Processing: ${stats.processing}
Completed: ${stats.completed}
Total Waste: ${stats.total_waste} Kg

MONTHLY WASTE
${monthlyWaste
  .map(
    (item) =>
      `${item.month}: ${item.waste} Kg`
  )
  .join("\n")}

WASTE TYPES
${wasteTypes
  .map(
    (item) =>
      `${item.name}: ${item.value} Kg`
  )
  .join("\n")}

========================================
Generated by Textile Waste AI
`;

    const blob = new Blob(
      [report],
      {
        type: "text/plain;charset=utf-8",
      }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download =
      "textile-waste-admin-report.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  // =========================================================
  // MAX MONTHLY VALUE
  // =========================================================

  const maxWaste =
    monthlyWaste.length > 0
      ? Math.max(
          ...monthlyWaste.map(
            (item) =>
              Number(item.waste) || 0
          )
        )
      : 1;

  // =========================================================
  // TOTAL WASTE TYPE
  // =========================================================

  const totalTypeWaste =
    wasteTypes.reduce(
      (total, item) =>
        total +
        (Number(item.value) || 0),
      0
    );

  // =========================================================
  // RENDER
  // =========================================================

  return (
    <div className="admin-reports-layout">

      {/* SIDEBAR */}

      <Sidebar
        collapsed={collapsed}
        setCollapsed={setCollapsed}
      />

      {/* MAIN CONTENT */}

      <div
        className={`admin-reports-content ${
          collapsed ? "collapsed" : ""
        }`}
      >

        <Navbar />

        <main className="admin-reports-page">

          {/* =================================================
              HEADER
          ================================================= */}

          <section className="admin-reports-hero">

            <div className="admin-reports-hero-left">

              <div className="admin-reports-hero-icon">
                <FaChartBar />
              </div>

              <div>

                <h1>
                  Admin Reports
                </h1>

                <p>
                  Monitor users, textile waste,
                  inventory and platform performance.
                </p>

              </div>

            </div>

            <div className="admin-reports-actions">

              <button
                type="button"
                className="refresh-report-btn"
                onClick={loadReports}
                disabled={loading}
              >
                <FaSyncAlt
                  className={
                    loading
                      ? "spin-icon"
                      : ""
                  }
                />

                {loading
                  ? "Refreshing..."
                  : "Refresh"}
              </button>

              <button
                type="button"
                className="download-report-btn"
                onClick={downloadReport}
              >
                <FaDownload />

                Download Report
              </button>

            </div>

          </section>

          {/* =================================================
              USER STATISTICS
          ================================================= */}

          <section className="report-section">

            <div className="report-section-heading">

              <div>
                <h2>
                  Platform Overview
                </h2>

                <p>
                  User and waste management
                  statistics.
                </p>
              </div>

            </div>

            <div className="report-stat-grid">

              <div className="report-stat-card blue">

                <div className="report-stat-icon">
                  <FaUsers />
                </div>

                <div>
                  <span>
                    Total Users
                  </span>

                  <strong>
                    {stats.total_users}
                  </strong>
                </div>

              </div>

              <div className="report-stat-card purple">

                <div className="report-stat-icon">
                  <FaIndustry />
                </div>

                <div>
                  <span>
                    Manufacturers
                  </span>

                  <strong>
                    {stats.manufacturers}
                  </strong>
                </div>

              </div>

              <div className="report-stat-card green">

                <div className="report-stat-icon">
                  <FaRecycle />
                </div>

                <div>
                  <span>
                    Recyclers
                  </span>

                  <strong>
                    {stats.recyclers}
                  </strong>
                </div>

              </div>

              <div className="report-stat-card orange">

                <div className="report-stat-icon">
                  <FaUsers />
                </div>

                <div>
                  <span>
                    Managers
                  </span>

                  <strong>
                    {stats.managers}
                  </strong>
                </div>

              </div>

            </div>

          </section>

          {/* =================================================
              WASTE STATISTICS
          ================================================= */}

          <section className="report-section">

            <div className="report-section-heading">

              <div>
                <h2>
                  Waste Management
                </h2>

                <p>
                  Current waste inventory and
                  processing status.
                </p>
              </div>

            </div>

            <div className="report-stat-grid">

              <div className="report-stat-card cyan">

                <div className="report-stat-icon">
                  <FaBoxes />
                </div>

                <div>
                  <span>
                    Inventory Records
                  </span>

                  <strong>
                    {stats.inventory}
                  </strong>
                </div>

              </div>

              <div className="report-stat-card yellow">

                <div className="report-stat-icon">
                  <FaClipboardList />
                </div>

                <div>
                  <span>
                    Pending
                  </span>

                  <strong>
                    {stats.pending}
                  </strong>
                </div>

              </div>

              <div className="report-stat-card blue">

                <div className="report-stat-icon">
                  <FaChartLine />
                </div>

                <div>
                  <span>
                    Processing
                  </span>

                  <strong>
                    {stats.processing}
                  </strong>
                </div>

              </div>

              <div className="report-stat-card green">

                <div className="report-stat-icon">
                  <FaRecycle />
                </div>

                <div>
                  <span>
                    Completed
                  </span>

                  <strong>
                    {stats.completed}
                  </strong>
                </div>

              </div>

            </div>

          </section>

          {/* =================================================
              TOTAL WASTE
          ================================================= */}

          <section className="total-waste-card">

            <div className="total-waste-icon">
              <FaWeightHanging />
            </div>

            <div>

              <span>
                Total Waste Managed
              </span>

              <strong>
                {Number(
                  stats.total_waste || 0
                ).toLocaleString()}{" "}
                Kg
              </strong>

              <p>
                Total textile waste recorded
                in the platform.
              </p>

            </div>

          </section>

          {/* =================================================
              CHARTS
          ================================================= */}

          <div className="reports-chart-grid">

            {/* MONTHLY WASTE */}

            <section className="report-chart-card">

              <div className="chart-card-header">

                <div>
                  <h2>
                    Monthly Waste Collection
                  </h2>

                  <p>
                    Waste generated across
                    recent months.
                  </p>
                </div>

                <FaChartLine />

              </div>

              <div className="monthly-chart">

                {monthlyWaste.length === 0 ? (

                  <div className="empty-chart">
                    No monthly data available.
                  </div>

                ) : (

                  monthlyWaste.map(
                    (item, index) => {

                      const value =
                        Number(
                          item.waste
                        ) || 0;

                      const height =
                        Math.max(
                          (value /
                            maxWaste) *
                            100,
                          5
                        );

                      return (

                        <div
                          className="chart-column"
                          key={`${item.month}-${index}`}
                        >

                          <div className="chart-value">
                            {value}
                          </div>

                          <div className="chart-bar-area">

                            <div
                              className="chart-bar"
                              style={{
                                height:
                                  `${height}%`,
                              }}
                            />

                          </div>

                          <span>
                            {item.month}
                          </span>

                        </div>

                      );
                    }
                  )

                )}

              </div>

            </section>

            {/* WASTE TYPES */}

            <section className="report-chart-card">

              <div className="chart-card-header">

                <div>
                  <h2>
                    Waste Type Distribution
                  </h2>

                  <p>
                    Breakdown by material type.
                  </p>
                </div>

                <FaRecycle />

              </div>

              <div className="waste-type-list">

                {wasteTypes.length === 0 ? (

                  <div className="empty-chart">
                    No waste type data available.
                  </div>

                ) : (

                  wasteTypes.map(
                    (item, index) => {

                      const value =
                        Number(
                          item.value
                        ) || 0;

                      const percentage =
                        totalTypeWaste > 0
                          ? (
                              (value /
                                totalTypeWaste) *
                              100
                            ).toFixed(1)
                          : 0;

                      return (

                        <div
                          className="waste-type-row"
                          key={`${item.name}-${index}`}
                        >

                          <div className="waste-type-top">

                            <span>
                              {item.name ||
                                "Unknown"}
                            </span>

                            <strong>
                              {value} Kg
                            </strong>

                          </div>

                          <div className="waste-type-progress">

                            <div
                              className="waste-type-progress-fill"
                              style={{
                                width:
                                  `${percentage}%`,
                              }}
                            />

                          </div>

                          <small>
                            {percentage}% of
                            total waste
                          </small>

                        </div>

                      );
                    }
                  )

                )}

              </div>

            </section>

          </div>

        </main>

      </div>

    </div>
  );
}

export default AdminReports;