import { useEffect, useState } from "react";
import TextileManagerSidebar from "../../components/TextileManagerSidebar";
import API from "../../api/auth";
import "../../styles/Textile-manager/AIPredictions.css";

function AIPredictions() {
  const [prediction, setPrediction] = useState(null);
  const [latestPredictions, setLatestPredictions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  // ============================================================
  // FETCH LATEST 5 PREDICTIONS
  // ============================================================

  const fetchPredictions = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await API.get("/upload/predictions");

      const data = Array.isArray(response.data)
        ? response.data
        : [];

      setLatestPredictions(data);

      // Latest prediction
      if (data.length > 0) {
        setPrediction(data[0]);
      } else {
        setPrediction(null);
      }
    } catch (err) {
      console.error(
        "Failed to fetch AI predictions:",
        err
      );

      setError(
        err.response?.data?.detail ||
          "Unable to load AI predictions."
      );
    } finally {
      setLoading(false);
    }
  };

  // ============================================================
  // LOAD WHEN PAGE OPENS
  // ============================================================

  useEffect(() => {
    fetchPredictions();
  }, []);

  // ============================================================
  // DOWNLOAD REPORT
  // ============================================================

  const handleDownloadReport = () => {
    if (!prediction) return;

    const report = `
TEXTILE WASTE INTELLIGENCE PLATFORM
AI PREDICTION REPORT
====================================

File Name: ${prediction.filename}

Material Type: ${prediction.material}
Confidence: ${prediction.confidence}%

Waste Type: ${prediction.waste_type}

Recyclability: ${prediction.recycle}
Reuse Potential: ${prediction.reuse}
Repair Potential: ${prediction.repair}

Sustainability Score: ${prediction.score}/100

====================================
Generated by Textile Manager AI Analysis
`;

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download =
      "textile-ai-prediction-report.txt";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  // ============================================================
  // SELECT ONE OF LATEST 5
  // ============================================================

  const handleSelectPrediction = (item) => {
    setPrediction(item);
  };

  // ============================================================
  // FORMAT DATE
  // ============================================================

  const formatDate = (date) => {
    if (!date) return "N/A";

    return new Date(date).toLocaleString();
  };

  // ============================================================
  // UI
  // ============================================================

  return (
    <div className="tm-ai-layout">

      <TextileManagerSidebar />

      <main className="tm-ai-content">

        {/* ====================================================
            HEADER
        ==================================================== */}

        <header className="tm-ai-header">
          <div>

            <span className="tm-ai-label">
              AI-POWERED TEXTILE INTELLIGENCE
            </span>

            <h1>
              AI Predictions
            </h1>

            <p>
              View AI-powered textile material and waste
              predictions generated from uploaded images.
            </p>

          </div>
        </header>


        {/* ====================================================
            ERROR
        ==================================================== */}

        {error && (
          <div className="tm-ai-error">
            {error}
          </div>
        )}


        {/* ====================================================
            LOADING
        ==================================================== */}

        {loading ? (

          <section className="tm-ai-result-card">

            <div className="tm-ai-loading">
              Loading AI predictions...
            </div>

          </section>

        ) : (

          <>

            {/* ==================================================
                LATEST PREDICTION
            ================================================== */}

            {prediction ? (

              <section className="tm-ai-result-card">

                <div className="tm-ai-result-header">

                  <div>

                    <span className="tm-ai-result-label">
                      AI PREDICTION RESULT
                    </span>

                    <h2>
                      Prediction Complete
                    </h2>

                    <p>
                      AI analysis result for the selected
                      uploaded textile image.
                    </p>

                  </div>


                  <div className="tm-ai-confidence">

                    <strong>
                      {prediction.confidence}%
                    </strong>

                    <span>
                      Confidence
                    </span>

                  </div>

                </div>


                {/* ==================================================
                    RESULT GRID
                ================================================== */}

                <div className="tm-ai-result-grid">

                  <div className="tm-ai-result-item">

                    <span>
                      Material Type
                    </span>

                    <strong>
                      {prediction.material || "N/A"}
                    </strong>

                  </div>


                  <div className="tm-ai-result-item">

                    <span>
                      Waste Type
                    </span>

                    <strong>
                      {prediction.waste_type || "N/A"}
                    </strong>

                  </div>


                  <div className="tm-ai-result-item">

                    <span>
                      Recyclability
                    </span>

                    <strong>
                      {prediction.recycle || "N/A"}
                    </strong>

                  </div>


                  <div className="tm-ai-result-item">

                    <span>
                      Reuse Potential
                    </span>

                    <strong>
                      {prediction.reuse || "N/A"}
                    </strong>

                  </div>


                  <div className="tm-ai-result-item">

                    <span>
                      Repair Potential
                    </span>

                    <strong>
                      {prediction.repair || "N/A"}
                    </strong>

                  </div>


                  <div className="tm-ai-result-item">

                    <span>
                      Sustainability Score
                    </span>

                    <strong>
                      {prediction.score ?? 0}/100
                    </strong>

                  </div>

                </div>


                {/* ==================================================
                    FILE INFORMATION
                ================================================== */}

                <div className="tm-ai-file-info">

                  <div>

                    <span>
                      File
                    </span>

                    <strong>
                      {prediction.filename}
                    </strong>

                  </div>


                  <div>

                    <span>
                      Analyzed
                    </span>

                    <strong>
                      {formatDate(
                        prediction.created_at
                      )}
                    </strong>

                  </div>

                </div>


                {/* ==================================================
                    ACTIONS
                ================================================== */}

                <div className="tm-ai-actions">

                  <button
                    type="button"
                    className="tm-ai-download-button"
                    onClick={handleDownloadReport}
                  >
                    ↓ Download Report
                  </button>


                  <button
                    type="button"
                    className="tm-ai-new-button"
                    onClick={fetchPredictions}
                  >
                    Refresh Predictions
                  </button>

                </div>

              </section>

            ) : (

              <section className="tm-ai-result-card">

                <div className="tm-ai-empty">

                  <h2>
                    No AI Predictions Yet
                  </h2>

                  <p>
                    Upload a textile image from the
                    Upload Textile section to generate
                    your first AI prediction.
                  </p>

                </div>

              </section>

            )}


            {/* ==================================================
                LATEST 5
            ================================================== */}

            <section className="tm-ai-history-card">

              <div className="tm-ai-card-heading">

                <div>

                  <span className="tm-ai-result-label">
                    RECENT AI ANALYSIS
                  </span>

                  <h2>
                    Latest 5 Predictions
                  </h2>

                  <p>
                    Your five most recent textile AI predictions.
                  </p>

                </div>

              </div>


              {latestPredictions.length === 0 ? (

                <div className="tm-ai-empty">

                  No prediction history available.

                </div>

              ) : (

                <div className="tm-ai-history-list">

                  {latestPredictions.map(
                    (item, index) => (

                      <button
                        key={item.id}
                        type="button"
                        className={`tm-ai-history-item ${
                          prediction?.id === item.id
                            ? "active"
                            : ""
                        }`}
                        onClick={() =>
                          handleSelectPrediction(item)
                        }
                      >

                        <div className="tm-ai-history-number">
                          {index + 1}
                        </div>


                        <div className="tm-ai-history-main">

                          <strong>
                            {item.material ||
                              "Unknown Material"}
                          </strong>

                          <span>
                            {item.filename}
                          </span>

                        </div>


                        <div className="tm-ai-history-confidence">

                          <strong>
                            {item.confidence}%
                          </strong>

                          <span>
                            Confidence
                          </span>

                        </div>


                        <div className="tm-ai-history-waste">

                          <strong>
                            {item.waste_type || "N/A"}
                          </strong>

                          <span>
                            Waste Type
                          </span>

                        </div>


                        <div className="tm-ai-history-date">

                          {formatDate(
                            item.created_at
                          )}

                        </div>

                      </button>

                    )
                  )}

                </div>

              )}

            </section>

          </>

        )}


        {/* ====================================================
            INFORMATION
        ==================================================== */}

        <section className="tm-ai-info">

          <div className="tm-ai-info-icon">
            ♻
          </div>

          <div>

            <h3>
              Intelligent Textile Analysis
            </h3>

            <p>
              AI predictions use the trained textile
              classification model and stored analysis
              results to support textile waste management
              decisions.
            </p>

          </div>

        </section>


        <footer className="tm-ai-footer">
          Textile Waste Intelligence Platform • AI Predictions
        </footer>

      </main>

    </div>
  );
}

export default AIPredictions;